import XCTest
import MLX
@testable import RVCNativeFeature

@MainActor
final class RVCNativeFeatureTests: XCTestCase {
    
    func testPthConversion() async throws {
        // Path to the dummy file generated by Python script
        let fileManager = FileManager.default
        let currentDir = URL(fileURLWithPath: fileManager.currentDirectoryPath)
        
        let possiblePath = currentDir.appendingPathComponent("../tests/dummy.pth")
        let standardPath = currentDir.appendingPathComponent("tests/dummy.pth")
        
        var dummyPth = standardPath
        if fileManager.fileExists(atPath: possiblePath.path) {
            dummyPth = possiblePath
        } else if fileManager.fileExists(atPath: standardPath.path) {
            dummyPth = standardPath
        } else {
             // Fallback
             dummyPth = URL(fileURLWithPath: "/Users/mcruz/Developer/Retrieval-based-Voice-Conversion-MLX/Demos/iOS/RVCNative/tests/dummy.pth")
        }
        
        var testFileUrl = dummyPth
        
        print("Testing with file at: \(testFileUrl.path)")
        
        guard fileManager.fileExists(atPath: testFileUrl.path) else {
             XCTFail("No test file found.")
             return
        }
        
        // Run conversion
        // Run conversion
        let converter = PthConverter.shared
        
        final class ConversionState: @unchecked Sendable {
            var progressCalled = false
            var lastProgress = 0.0
        }
        let state = ConversionState()
        
        let arrays = try converter.convert(url: testFileUrl) { progress, msg in
             print("Progress: \(progress) - \(msg)")
             state.progressCalled = true
             state.lastProgress = progress
        }
        
        XCTAssertTrue(state.progressCalled, "Progress callback should have been called")
        
        // Assertions
        XCTAssertFalse(arrays.isEmpty, "Resulting dictionary should not be empty")
        print("Successfully converted \(arrays.count) tensors.")
        if let first = arrays.keys.first {
            print("Sample key: \(first), Shape: \(arrays[first]?.shape ?? [])")
        }
        
        print("Conversion test passed!")
    }
}
